# Generated by Django 6.1.1 on 2026-09-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_skill_user_avatar_user_phone_jobseekerprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
